#!/usr/bin/env python3
"""Generate the three persistence-enabled Filebench workloads used here."""

from __future__ import annotations

import argparse
import pathlib


PROFILES = {
    "fileserver": {
        "filesize": "256k",
        "body": """
    flowop createfile name=create1,filesetname=bigfileset,fd=1
    flowop writewholefile name=write1,srcfd=1,fd=1,iosize=256k
    flowop fsync name=sync1,fd=1
    flowop closefile name=closewrite1,fd=1
    flowop openfile name=openwrite2,filesetname=bigfileset,fd=1
    flowop appendfilerand name=write2,fd=1,iosize=256k
    flowop fsync name=sync2,fd=1
    flowop closefile name=closewrite2,fd=1
    flowop openfile name=openread,filesetname=bigfileset,fd=1
    flowop readwholefile name=read,fd=1,iosize=1m
    flowop closefile name=closeread,fd=1
    flowop deletefile name=delete1,filesetname=bigfileset
    flowop statfile name=stat,filesetname=bigfileset
""",
    },
    "webproxy": {
        "filesize": "2m",
        "body": """
    flowop deletefile name=delete1,filesetname=bigfileset
    flowop createfile name=create1,filesetname=bigfileset,fd=1
    flowop appendfilerand name=write,fd=1,iosize=256k
    flowop fsync name=sync,fd=1
    flowop closefile name=closewrite,fd=1
    flowop openfile name=openread,filesetname=bigfileset,fd=1
    flowop readwholefile name=read1,fd=1,iosize=1m
    flowop readwholefile name=read2,fd=1,iosize=1m
    flowop readwholefile name=read3,fd=1,iosize=1m
    flowop readwholefile name=read4,fd=1,iosize=1m
    flowop readwholefile name=read5,fd=1,iosize=1m
    flowop closefile name=closeread,fd=1
""",
    },
    "varmail": {
        "filesize": "64k",
        "body": """
    flowop deletefile name=delete1,filesetname=bigfileset
    flowop createfile name=create1,filesetname=bigfileset,fd=1
    flowop appendfilerand name=write1,fd=1,iosize=64k
    flowop fsync name=sync1,fd=1
    flowop closefile name=closewrite1,fd=1
    flowop openfile name=openwrite,filesetname=bigfileset,fd=1
    flowop readwholefile name=read1,fd=1,iosize=1m
    flowop appendfilerand name=write2,fd=1,iosize=64k
    flowop fsync name=sync2,fd=1
    flowop closefile name=closewrite,fd=1
    flowop openfile name=openread,filesetname=bigfileset,fd=1
    flowop readwholefile name=read2,fd=1,iosize=1m
    flowop closefile name=closeread,fd=1
    flowop statfile name=stat,filesetname=bigfileset
""",
    },
}


def generate(workload: str, directory: str, threads: int, scale: str) -> str:
    profile = PROFILES[workload]
    # prealloc=80 leaves only 20% of the fileset available to createfile.
    # Keep the smoke fileset comfortably above the 16 concurrent creators;
    # 64 entries can stop immediately with "could not obtain a file".
    nfiles = 10000 if scale == "paper" else 256
    # Match the three workloads bundled with the patched Filebench build.  A
    # single million-entry directory measures same-parent exclusion, not the
    # independent-parent namespace concurrency exercised by these workloads.
    dirwidth = 100
    runtime = 60 if scale == "paper" else 5
    return f"""# Generated by generate_filebench_workload.py.
# /Or is the explicit prefix understood by both OrchFS wrappers. Absolute
# workload and shared-memory paths outside /Or remain host paths.
set $dir={directory}
set $nfiles={nfiles}
set $nthreads={threads}
set $runtime={runtime}
set $filesize={profile['filesize']}

define fileset name=bigfileset,path=$dir,size=$filesize,entries=$nfiles,dirwidth={dirwidth},prealloc=80

define process name=orchfsbench,instances=1
{{
  thread name=worker,memsize=10m,instances=$nthreads
  {{{profile['body']}  }}
}}

echo "OrchFS {workload} differential workload loaded"
run $runtime
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workload", choices=sorted(PROFILES))
    parser.add_argument("--directory", required=True)
    parser.add_argument("--threads", required=True, type=int, choices=(1, 16))
    parser.add_argument("--scale", choices=("smoke", "paper"), default="smoke")
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    args.output.write_text(
        generate(args.workload, args.directory, args.threads, args.scale),
        encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
