#!/usr/bin/env bash
# Copy this file outside the checkout, edit every host-specific value, then:
#   source /path/to/orchfs-async.conf
# Sourcing this template never binds or formats a device.
# DAX selection and FILEBENCH remain compile-time overrides generated by
# config_parameter.py; config/config_template.h owns every shared knob.

# LibFS <-> KFS coroutine RPC endpoint and worker topology.
export ORCHFS_ASYNC_ENDPOINT="/tmp/orchfs-kfs.sock"
export ORCHFS_CLIENT_WORKERS="1"
export ORCHFS_CLIENT_LANES="4"
export ORCHFS_CLIENT_BLOCKING_SPINS="1024"
export ORCHFS_CLIENT_BLOCKING_SPIN_LIMIT="4"
export ORCHFS_CLIENT_BLOCKING_SPIN_WARMUP="64"
export ORCHFS_KFS_WORKERS="16"
export ORCHFS_IPC_RING_CAPACITY="64"
export ORCHFS_IPC_DATA_SLOT_SIZE="1048576"

# KFS-only SPDK controller selection. PCI BDF must include the domain. Leave
# the placeholder in place until nvme-cli/sysfs confirms the BDF-to-NSID map.
export ORCHFS_SPDK_PCI_BDF="0000:BB:DD.F"
export ORCHFS_SPDK_NSID="1"
# KFS creates one qpair per ORCHFS_KFS_WORKERS Runtime worker. This standalone
# poller count and CPU list apply only to the caller-polled mkfs formatter.
export ORCHFS_SPDK_POLLER_COUNT="4"
export ORCHFS_SPDK_QUEUE_DEPTH="32"
export ORCHFS_SPDK_BOUNCE_BUFFERS="32"
export ORCHFS_SPDK_MAX_TRANSFER_SIZE="1048576"
# Empty selects the first CPUs in the formatter's process affinity mask.
export ORCHFS_SPDK_CPU_LIST=""

# SPDK/DPDK environment. HUGEMEM is consumed by SPDK's setup.sh; the backend
# consumes HUGEPAGE_DIR and SHM_ID when KFS starts.
export ORCHFS_SPDK_HUGEMEM_MB="4096"
export ORCHFS_SPDK_HUGEPAGE_DIR="/dev/hugepages"
export ORCHFS_SPDK_SHM_ID="-1"
# Empty derives the standalone formatter's SPDK environment mask from
# ORCHFS_SPDK_CPU_LIST. Production KFS advertises one EAL control lcore while
# its Runtime workers directly poll all qpairs.
export ORCHFS_SPDK_REACTOR_MASK=""
